import TSPlusAPI from "@/services/ts-plus";
import type { CommandDefinition } from "@/types/command.types";


// Export a function to generate commands with the current translation function
import type { TFunction } from 'i18next';

export function getAvailableCommands(t: TFunction): CommandDefinition[] {
  return [
    {
      id: "backup_data",
      name: t("cmd_backup_data"),
      route: "/commands/backup_data",
      method: "POST",
      description: t("cmd_backup_data_desc"),
      params: [
        { id: "optionalPath", name: "Optional Path", type: "text", optional: true },
        { id: "silent", name: "Silent", type: "boolean", optional: true },
      ],
      api: TSPlusAPI.backupData,
    },
    {
      id: "restore_data",
      name: t("cmd_restore_data"),
      route: "/commands/restore_data/",
      method: "PUT",
      description: t("cmd_restore_data_desc"),
      params: [
        { id: "backupPath", name: "Backup Path", type: "text", optional: true },
        { id: "silent", name: "Silent", type: "boolean", optional: true },
      ],
      api: TSPlusAPI.restoreData,
    },
    {
      id: "update",
      name: t("cmd_update"),
      route: "/commands/update/",
      method: "PUT",
      description: t("cmd_update_desc"),
      params: [
        { id: "addons", name: "Addons", type: "boolean", optional: true }
      ],
      api: TSPlusAPI.update,
    },
    {
      id: "windows_compatibility",
      name: t("cmd_windows_compatibility"),
      route: "/commands/windows_compatibility/",
      method: "PUT",
      description: t("cmd_windows_compatibility_desc"),
      params: [
        { id: "silent", name: "Silent", type: "boolean", optional: true }
      ],
      api: TSPlusAPI.windowsCompatibility,
    },
    {
      id: "install_printer",
      name: t("cmd_install_printer"),
      route: "/commands/install_printer/",
      method: "POST",
      description: t("cmd_install_printer_desc"),
      params: [],
      api: TSPlusAPI.installPrinter,
    },
    {
      id: "remove_printer",
      name: t("cmd_remove_printer"),
      route: "/commands/remove_printer/",
      method: "DELETE",
      description: t("cmd_remove_printer_desc"),
      params: [],
      api: TSPlusAPI.removePrinter,
    },
    {
      id: "proxy_set",
      name: t("cmd_proxy_set"),
      route: "/commands/proxy_set/",
      method: "POST",
      description: t("cmd_proxy_set_desc"),
      params: [
        { id: "host", name: "Host", type: "text", optional: true },
        { id: "port", name: "Port", type: "number", optional: true },
        { id: "username", name: "Username", type: "text", optional: true },
        { id: "password", name: "Password", type: "text", optional: true },
      ],
      api: TSPlusAPI.proxySet,
    },
    {
      id: "web_credentials",
      name: t("cmd_web_credentials"),
      route: "/commands/web_credentials/",
      method: "POST",
      description: t("cmd_web_credentials_desc"),
      params: [],
      api: TSPlusAPI.webCredentials,
    },
    {
      id: "web_credentials_add",
      name: t("cmd_web_credentials_add"),
      route: "/commands/web_credentials_add/",
      method: "POST",
      description: t("cmd_web_credentials_add_desc"),
      params: [
        { id: "webLogin", name: "Web Login", type: "text", optional: false },
        { id: "webPassword", name: "Web Password", type: "text", optional: false },
        { id: "windowsLogin", name: "Windows Login", type: "text", optional: false },
        { id: "windowsPassword", name: "Windows Password", type: "text", optional: false },
        { id: "maximumConcurrentSessions", name: "Maximum Concurrent Sessions", type: "number", optional: true },
      ],
      api: TSPlusAPI.webCredentialsAdd,
    },
    {
      id: "web_credentials_remove",
      name: t("cmd_web_credentials_remove"),
      route: "/commands/web_credentials_remove/",
      method: "DELETE",
      description: t("cmd_web_credentials_remove_desc"),
      params: [
        { id: "webLogin", name: "Web Login", type: "text", optional: false },
      ],
      api: TSPlusAPI.webCredentialsRemove,
    },
    {
      id: "session_manager",
      name: t("cmd_session_manager"),
      route: "/commands/session_manager/",
      method: "POST",
      description: t("cmd_session_manager_desc"),
      params: [],
      api: TSPlusAPI.sessionManager,
    },
    {
      id: "farm_sessions_monitor",
      name: t("cmd_farm_sessions_monitor"),
      route: "/commands/farm_sessions_monitor/",
      method: "POST",
      description: t("cmd_farm_sessions_monitor_desc"),
      params: [],
      api: TSPlusAPI.farmSessionsMonitor,
    },
    {
      id: "farm_loadbalancing",
      name: t("cmd_farm_loadbalancing"),
      route: "/commands/farm_loadbalancing/",
      method: "POST",
      description: t("cmd_farm_loadbalancing_desc"),
      params: [],
      api: TSPlusAPI.farmLoadbalancing,
    },
    {
      id: "system_audit",
      name: t("cmd_system_audit"),
      route: "/commands/system_audit/",
      method: "POST",
      description: t("cmd_system_audit_desc"),
      params: [],
      api: TSPlusAPI.systemAudit,
    },
    {
      id: "activate_license",
      name: t("cmd_activate_license"),
      route: "/commands/activate_license/",
      method: "POST",
      description: t("cmd_activate_license_desc"),
      params: [
        { id: "licensePath", name: "License Path", type: "text", optional: false },
      ],
      api: TSPlusAPI.activateLicense,
    },
    {
      id: "license_reset",
      name: t("cmd_license_reset"),
      route: "/commands/license_reset/",
      method: "POST",
      description: t("cmd_license_reset_desc"),
      params: [],
      api: TSPlusAPI.licenseReset,
    },
    {
      id: "vl_activate",
      name: t("cmd_vl_activate"),
      route: "/commands/vl_activate/",
      method: "POST",
      description: t("cmd_vl_activate_desc"),
      params: [
        { id: "licensekey", name: "License Key", type: "text", optional: false },
        { id: "users", name: "Users", type: "text", optional: true },
        { id: "edition", name: "Edition", type: "text", optional: true },
        { id: "supportyears", name: "Support Years", type: "number", optional: true },
        { id: "comments", name: "Comments", type: "text", optional: true },
      ],
      api: TSPlusAPI.vlActivate,
    },
    {
      id: "vl_enable",
      name: t("cmd_vl_enable"),
      route: "/commands/vl_enable/",
      method: "POST",
      description: t("cmd_vl_enable_desc"),
      params: [
        { id: "licensekey", name: "License Key", type: "text", optional: false },
      ],
      api: TSPlusAPI.vlEnable,
    },
    {
      id: "vl_disable",
      name: t("cmd_vl_disable"),
      route: "/commands/vl_disable/",
      method: "POST",
      description: t("cmd_vl_disable_desc"),
      params: [
        { id: "licensekey", name: "License Key", type: "text", optional: false },
      ],
      api: TSPlusAPI.vlDisable,
    },
    {
      id: "vl_update",
      name: t("cmd_vl_update"),
      route: "/commands/vl_update/",
      method: "POST",
      description: t("cmd_vl_update_desc"),
      params: [
        { id: "licensekey", name: "License Key", type: "text", optional: false },
        { id: "users", name: "Users", type: "text", optional: true },
      ],
      api: TSPlusAPI.vlUpdate,
    },
    {
      id: "vl_credits_license",
      name: t("cmd_vl_credits_license"),
      route: "/commands/vl_credits_license/",
      method: "POST",
      description: t("cmd_vl_credits_license_desc"),
      params: [
        { id: "licensekey", name: "License Key", type: "text", optional: false },
        { id: "login", name: "Login", type: "text", optional: true },
        { id: "edition", name: "Edition", type: "text", optional: true },
        { id: "silent", name: "Silent", type: "boolean", optional: true },
      ],
      api: TSPlusAPI.vlCreditsLicense,
    },
    {
      id: "vl_credits_support",
      name: t("cmd_vl_credits_support"),
      route: "/commands/vl_credits_support/",
      method: "POST",
      description: t("cmd_vl_credits_support_desc"),
      params: [
        { id: "licensekey", name: "License Key", type: "text", optional: false },
        { id: "login", name: "Login", type: "text", optional: true },
        { id: "edition", name: "Edition", type: "text", optional: true },
        { id: "silent", name: "Silent", type: "boolean", optional: true },
      ],
      api: TSPlusAPI.vlCreditsSupport,
    },
    {
      id: "2fa_resetuser",
      name: t("cmd_2fa_resetuser"),
      route: "/commands/2fa_resetuser/",
      method: "POST",
      description: t("cmd_2fa_resetuser_desc"),
      params: [
        { id: "users", name: "Users", type: "string[]", optional: false },
      ],
      api: TSPlusAPI.twofaResetUser,
    },
    {
      id: "2fa_addusers",
      name: t("cmd_2fa_addusers"),
      route: "/commands/2fa_addusers/",
      method: "POST",
      description: t("cmd_2fa_addusers_desc"),
      params: [
        { id: "userInfos", name: "User Infos", type: "string[]", optional: false },
      ],
      api: TSPlusAPI.twofaAddUsers,
    },
    {
      id: "2fa_addgroups",
      name: t("cmd_2fa_addgroups"),
      route: "/commands/2fa_addgroups/",
      method: "POST",
      description: t("cmd_2fa_addgroups_desc"),
      params: [
        { id: "groups", name: "Groups", type: "string[]", optional: false },
      ],
      api: TSPlusAPI.twofaAddGroups,
    },
    {
      id: "2fa_getusers",
      name: t("cmd_2fa_getusers"),
      route: "/commands/2fa_getusers/",
      method: "GET",
      description: t("cmd_2fa_getusers_desc"),
      params: [],
      api: TSPlusAPI.twofaGetUsers,
    },
    {
      id: "2fa_deleteuser",
      name: t("cmd_2fa_deleteuser"),
      route: "/commands/2fa_deleteuser/",
      method: "DELETE",
      description: t("cmd_2fa_deleteuser_desc"),
      params: [
        { id: "domainName", name: "Domain Name", type: "text", optional: false },
        { id: "userType", name: "User Type", type: "text", optional: false },
      ],
      api: TSPlusAPI.twofaDeleteUser,
    },
    {
      id: "windowscredential_addorupdate",
      name: t("cmd_windowscredential_addorupdate"),
      route: "/commands/windowscredential_addorupdate/",
      method: "POST",
      description: t("cmd_windowscredential_addorupdate_desc"),
      params: [
        { id: "csvFilePath", name: "CSV File Path", type: "text", optional: true },
        { id: "target", name: "Target", type: "text", optional: true },
        { id: "username", name: "Username", type: "text", optional: true },
        { id: "password", name: "Password", type: "text", optional: true },
      ],
      api: TSPlusAPI.windowsCredentialAddorupdate,
    },
    {
      id: "windowscredential_remove",
      name: t("cmd_windowscredential_remove"),
      route: "/commands/windowscredential_remove/",
      method: "DELETE",
      description: t("cmd_windowscredential_remove_desc"),
      params: [
        { id: "csvFilePath", name: "CSV File Path", type: "text", optional: true },
        { id: "username", name: "Username", type: "text", optional: true },
      ],
      api: TSPlusAPI.windowsCredentialRemove,
    },
  ];
}
