import TSPlusAPI from "@/services/ts-plus";
import type { CommandDefinition } from "@/types/command.types";
import {
  // volumeActivationSchema,
  volumeEnableDisableSchema,
  volumeInstallSchema,
} from "@/schemas/ts-plusCommandsSchema";

const AVAILABLE_COMMANDS: CommandDefinition[] = [
  {
    id: "backup_data",
    name: "Backup Data Settings",
    route: "/commands/backup_data",
    method: "POST",
    description: "Command /backup is used to backup TSplus data and settings.",
    params: [
      { id: "optionalPath", name: "Optional Path", type: "string", optional: true },
      { id: "silent", name: "Silent", type: "boolean", optional: true },
    ],
    api: TSPlusAPI.backupData,
  },
  {
    id: "restore_data",
    name: "Restore Data Settings",
    route: "/commands/restore_data/",
    method: "PUT",
    description: "Command /restore is used to restore TSplus data and settings from a backup.",
    params: [
      { id: "backupPath", name: "Backup Path", type: "string", optional: true },
      { id: "silent", name: "Silent", type: "boolean", optional: true },
    ],
    api: TSPlusAPI.restoreData,
  },
  {
    id: "update",
    name: "Update",
    route: "/commands/update/",
    method: "PUT",
    description: "Command /update is used to update TSplus to the latest version.",
    params: [
      { id: "addons", name: "Addons", type: "boolean", optional: true }
    ],
    api: TSPlusAPI.update,
  },
  {
    id: "windows_compatibility",
    name: "Windows Compatibility Updates",
    route: "/commands/windows_compatibility/",
    method: "PUT",
    description: "Command to apply Windows compatibility updates.",
    params: [
      { id: "silent", name: "Silent", type: "boolean", optional: true }
    ],
    api: TSPlusAPI.windowsCompatibility,
  },
  {
    id: "install_printer",
    name: "Install Universal Printer",
    route: "/commands/install_printer/",
    method: "POST",
    description: "Command to install the TSplus Universal Printer.",
    params: [],
    api: TSPlusAPI.installPrinter,
  },
  {
    id: "remove_printer",
    name: "Remove Universal Printer",
    route: "/commands/remove_printer/",
    method: "DELETE",
    description: "Command to remove the TSplus Universal Printer.",
    params: [],
    api: TSPlusAPI.removePrinter,
  },
  {
    id: "proxy_set",
    name: "Proxy Set",
    route: "/commands/proxy_set/",
    method: "POST",
    description: "Command to configure the proxy server for TSplus.",
    params: [
      { id: "host", name: "Host", type: "string", optional: true },
      { id: "port", name: "Port", type: "number", optional: true },
      { id: "username", name: "Username", type: "string", optional: true },
      { id: "password", name: "Password", type: "string", optional: true },
    ],
    api: TSPlusAPI.proxySet,
  },
  {
    id: "web_credentials",
    name: "Web Credentials",
    route: "/commands/web_credentials/",
    method: "POST",
    description: "Command to open the Web Credentials form.",
    params: [],
    api: TSPlusAPI.webCredentials,
  },
  {
    id: "web_credentials_add",
    name: "Web Credentials Add",
    route: "/commands/web_credentials_add/",
    method: "POST",
    description: "Command to add new Web Credentials.",
    params: [
      { id: "webLogin", name: "Web Login", type: "string", optional: false },
      { id: "webPassword", name: "Web Password", type: "string", optional: false },
      { id: "windowsLogin", name: "Windows Login", type: "string", optional: false },
      { id: "windowsPassword", name: "Windows Password", type: "string", optional: false },
      { id: "maximumConcurrentSessions", name: "Maximum Concurrent Sessions", type: "number", optional: true },
    ],
    api: TSPlusAPI.webCredentialsAdd,
  },
  {
    id: "web_credentials_remove",
    name: "Web Credentials Remove",
    route: "/commands/web_credentials_remove/",
    method: "DELETE",
    description: "Command to remove Web Credentials.",
    params: [
      { id: "webLogin", name: "Web Login", type: "string", optional: false },
    ],
    api: TSPlusAPI.webCredentialsRemove,
  },
  {
    id: "session_manager",
    name: "Session Manager",
    route: "/commands/session_manager/",
    method: "POST",
    description: "Command to open the Session Manager.",
    params: [],
    api: TSPlusAPI.sessionManager,
  },
  {
    id: "farm_sessions_monitor",
    name: "Farm Sessions Monitor",
    route: "/commands/farm_sessions_monitor/",
    method: "POST",
    description: "Command to open the Farm Sessions Monitor.",
    params: [],
    api: TSPlusAPI.farmSessionsMonitor,
  },
  {
    id: "farm_loadbalancing",
    name: "Farm LoadBalancing",
    route: "/commands/farm_loadbalancing/",
    method: "POST",
    description: "Command to open the Load Balancing Manager.",
    params: [],
    api: TSPlusAPI.farmLoadbalancing,
  },
  {
    id: "system_audit",
    name: "System Audit",
    route: "/commands/system_audit/",
    method: "POST",
    description: "Command to run a system audit.",
    params: [],
    api: TSPlusAPI.systemAudit,
  },
  {
    id: "activate_license",
    name: "Activate License",
    route: "/commands/activate_license/",
    method: "POST",
    description: "Command to activate a TSplus license.",
    params: [
      { id: "licensePath", name: "License Path", type: "string", optional: false },
    ],
    api: TSPlusAPI.activateLicense,
  },
  {
    id: "license_reset",
    name: "License Reset",
    route: "/commands/license_reset/",
    method: "POST",
    description: "Command to reset the TSplus license after VM cloning.",
    params: [],
    api: TSPlusAPI.licenseReset,
  },
  {
    id: "vl_activate",
    name: "Volume License Activate",
    route: "/commands/vl_activate/",
    method: "POST",
    description: "Command to activate a Volume License.",
    params: [
      { id: "licensekey", name: "License Key", type: "string", optional: false },
      { id: "users", name: "Users", type: "string", optional: true },
      { id: "edition", name: "Edition", type: "string", optional: true },
      { id: "supportyears", name: "Support Years", type: "number", optional: true },
      { id: "comments", name: "Comments", type: "string", optional: true },
    ],
    api: TSPlusAPI.vlActivate,
  },
  {
    id: "vl_enable",
    name: "Volume License Enable",
    route: "/commands/vl_enable/",
    method: "POST",
    description: "Command to enable a Volume License.",
    params: [
      { id: "licensekey", name: "License Key", type: "string", optional: false },
    ],
    api: TSPlusAPI.vlEnable,
  },
  {
    id: "vl_disable",
    name: "Volume License Disable",
    route: "/commands/vl_disable/",
    method: "POST",
    description: "Command to disable a Volume License.",
    params: [
      { id: "licensekey", name: "License Key", type: "string", optional: false },
    ],
    api: TSPlusAPI.vlDisable,
  },
  {
    id: "vl_update",
    name: "Volume License Update",
    route: "/commands/vl_update/",
    method: "POST",
    description: "Command to update a Volume License.",
    params: [
      { id: "licensekey", name: "License Key", type: "string", optional: false },
      { id: "users", name: "Users", type: "string", optional: true },
    ],
    api: TSPlusAPI.vlUpdate,
  },
  {
    id: "vl_credits_license",
    name: "Volume License Credits License",
    route: "/commands/vl_credits_license/",
    method: "POST",
    description: "Command to display remaining license credits for a Volume License key.",
    params: [
      { id: "licensekey", name: "License Key", type: "string", optional: false },
      { id: "login", name: "Login", type: "string", optional: true },
      { id: "edition", name: "Edition", type: "string", optional: true },
      { id: "silent", name: "Silent", type: "boolean", optional: true },
    ],
    api: TSPlusAPI.vlCreditsLicense,
  },
  {
    id: "vl_credits_support",
    name: "Volume License Credits Support",
    route: "/commands/vl_credits_support/",
    method: "POST",
    description: "Command to display remaining support credits for a Volume License key.",
    params: [
      { id: "licensekey", name: "License Key", type: "string", optional: false },
      { id: "login", name: "Login", type: "string", optional: true },
      { id: "edition", name: "Edition", type: "string", optional: true },
      { id: "silent", name: "Silent", type: "boolean", optional: true },
    ],
    api: TSPlusAPI.vlCreditsSupport,
  },
  {
    id: "2fa_resetuser",
    name: "2FA Reset User",
    route: "/commands/2fa_resetuser/",
    method: "POST",
    description: "Command to reset 2FA for users.",
    params: [
      { id: "users", name: "Users", type: "string[]", optional: false },
    ],
    api: TSPlusAPI.twofaResetUser,
  },
  {
    id: "2fa_addusers",
    name: "2FA Add Users",
    route: "/commands/2fa_addusers/",
    method: "POST",
    description: "Command to add users to 2FA.",
    params: [
      { id: "userInfos", name: "User Infos", type: "string[]", optional: false },
    ],
    api: TSPlusAPI.twofaAddUsers,
  },
  {
    id: "2fa_addgroups",
    name: "2FA Add Groups",
    route: "/commands/2fa_addgroups/",
    method: "POST",
    description: "Command to add groups to 2FA.",
    params: [
      { id: "groups", name: "Groups", type: "string[]", optional: false },
    ],
    api: TSPlusAPI.twofaAddGroups,
  },
  {
    id: "2fa_getusers",
    name: "2FA Get Users",
    route: "/commands/2fa_getusers/",
    method: "GET",
    description: "Command to list users registered for 2FA.",
    params: [],
    api: TSPlusAPI.twofaGetUsers,
  },
  {
    id: "2fa_deleteuser",
    name: "2FA Delete User",
    route: "/commands/2fa_deleteuser/",
    method: "DELETE",
    description: "Command to delete a user or group from 2FA.",
    params: [
      { id: "domainName", name: "Domain Name", type: "string", optional: false },
      { id: "userType", name: "User Type", type: "string", optional: false },
    ],
    api: TSPlusAPI.twofaDeleteUser,
  },
  {
    id: "windowscredential_addorupdate",
    name: "Windows Credential AddOrUpdate",
    route: "/commands/windowscredential_addorupdate/",
    method: "POST",
    description: "Command to add or update credentials in the Windows Credentials Manager.",
    params: [
      { id: "csvFilePath", name: "CSV File Path", type: "string", optional: true },
      { id: "target", name: "Target", type: "string", optional: true },
      { id: "username", name: "Username", type: "string", optional: true },
      { id: "password", name: "Password", type: "string", optional: true },
    ],
    api: TSPlusAPI.windowsCredentialAddorupdate,
  },
  {
    id: "windowscredential_remove",
    name: "Windows Credential Remove",
    route: "/commands/windowscredential_remove/",
    method: "DELETE",
    description: "Command to remove credentials from the Windows Credentials Manager.",
    params: [
      { id: "csvFilePath", name: "CSV File Path", type: "string", optional: true },
      { id: "username", name: "Username", type: "string", optional: true },
    ],
    api: TSPlusAPI.windowsCredentialRemove,
  },
];

export default AVAILABLE_COMMANDS;
